import json
import logging
import os
from typing import Any, Dict, Optional
from urllib import error, request

from dotenv import load_dotenv

load_dotenv()

logger = logging.getLogger(__name__)


class GeminiService:
    """Generate educational nutrition recommendations from the ML prediction."""

    def __init__(self, api_key: Optional[str] = None):
        load_dotenv()
        self.api_key = api_key or os.getenv("GEMINI_API_KEY")
        self.endpoint = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent"

    def _build_prompt(self, context: Dict[str, Any]) -> str:
        return f"""You are a nutrition education assistant.
You must not diagnose disease or override the machine learning prediction.
The prediction below is already generated by a trained model.
Your role is to explain it in plain language and suggest general nutrition and lifestyle guidance.

User details:
- Age: {context.get('age', 'Not provided')}
- Gender: {context.get('gender', 'Not provided')}
- Lifestyle: {json.dumps(context.get('lifestyle', {}), ensure_ascii=False)}
- Symptoms: {', '.join(context.get('symptoms', [])) or 'None reported'}
- Laboratory values: {json.dumps(context.get('laboratory_values', {}), ensure_ascii=False)}
- Predicted deficiency: {context.get('predicted_deficiency', 'Unknown')}
- Confidence score: {context.get('confidence_score', 'Unknown')}%

Instructions:
1. Respond in JSON only.
2. Use keys: explanation, foods_to_eat, foods_to_limit, lifestyle_recommendations, disclaimer.
3. explanation should be a short plain-language explanation.
4. foods_to_eat, foods_to_limit, lifestyle_recommendations should be arrays of short strings.
5. disclaimer should clearly state that this is an AI-generated educational recommendation and not a medical diagnosis.
6. Do not ask for a diagnosis or claim certainty beyond the provided prediction.
"""

    def _fallback_recommendation(self, message: str, context: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        prediction = str(context.get("predicted_deficiency", "your assessment") if context else "your assessment")
        prediction_lower = prediction.lower()

        if "iron" in prediction_lower:
            foods_to_eat = ["Iron-rich lean red meat, beans, or lentils", "Spinach and fortified cereals"]
            foods_to_limit = ["Coffee or tea with meals", "Highly processed snacks"]
            lifestyle_recommendations = ["Pair iron-rich foods with vitamin C sources", "Maintain regular rest and light exercise"]
        elif "vitamin d" in prediction_lower:
            foods_to_eat = ["Fatty fish, eggs, and fortified dairy", "Sunlight exposure when appropriate"]
            foods_to_limit = ["Excess alcohol", "Very low-calorie diets"]
            lifestyle_recommendations = ["Spend some time outdoors safely", "Keep a consistent sleep routine"]
        elif "b12" in prediction_lower:
            foods_to_eat = ["Fish, eggs, dairy, or fortified plant foods", "Balanced meals with protein"]
            foods_to_limit = ["Skipping meals repeatedly", "Very restrictive diets"]
            lifestyle_recommendations = ["Eat regular meals with protein", "Monitor symptoms and seek medical guidance if they persist"]
        elif "vitamin c" in prediction_lower:
            foods_to_eat = ["Citrus fruits, berries, and peppers", "Vegetables and soups rich in nutrients"]
            foods_to_limit = ["Excess sugar-sweetened drinks", "Highly processed convenience meals"]
            lifestyle_recommendations = ["Include fresh produce in most meals", "Stay hydrated throughout the day"]
        elif "calcium" in prediction_lower:
            foods_to_eat = ["Dairy products or fortified alternatives", "Leafy greens and sesame seeds"]
            foods_to_limit = ["Excess salty processed foods", "Very low dairy intake"]
            lifestyle_recommendations = ["Keep your activity level steady", "Support bone health with regular movement"]
        else:
            foods_to_eat = ["Balanced meals with vegetables and protein", "Whole grains and dairy or fortified alternatives"]
            foods_to_limit = ["Excess sugar and fast food", "Large amounts of alcohol"]
            lifestyle_recommendations = ["Stay hydrated and maintain regular sleep", "Discuss concerns with a healthcare professional"]

        if context and context.get("symptoms"):
            symptoms = [str(item) for item in context.get("symptoms", []) if str(item)]
            if symptoms:
                lifestyle_recommendations.append(f"Monitor symptoms such as {', '.join(symptoms[:3])}")

        return {
            "available": True,
            "message": message,
            "explanation": f"The prediction suggests {prediction}. These general nutrition suggestions are being provided because Gemini AI is currently unavailable.",
            "foods_to_eat": foods_to_eat,
            "foods_to_limit": foods_to_limit,
            "lifestyle_recommendations": lifestyle_recommendations,
            "disclaimer": "This is an AI-generated educational recommendation. It is not a medical diagnosis. Please consult a qualified healthcare professional for medical advice.",
        }

    def get_recommendation(self, context: Dict[str, Any]) -> Dict[str, Any]:
        if not self.api_key:
            return self._fallback_recommendation("Gemini API key is not configured. Using built-in nutrition guidance instead.", context)

        prompt = self._build_prompt(context)
        payload = {
            "contents": [{"parts": [{"text": prompt}]}],
            "generationConfig": {"temperature": 0.3, "maxOutputTokens": 800},
        }

        try:
            data = json.dumps(payload).encode("utf-8")
            req = request.Request(
                f"{self.endpoint}?key={self.api_key}",
                data=data,
                headers={"Content-Type": "application/json"},
                method="POST",
            )
            with request.urlopen(req, timeout=20) as response:
                body = response.read().decode("utf-8")
                parsed = json.loads(body)

            text = parsed.get("candidates", [{}])[0].get("content", {}).get("parts", [{}])[0].get("text", "")
            cleaned = text.strip()
            if cleaned.startswith("```"):
                cleaned = cleaned.strip("`").strip()
                if cleaned.startswith("json"):
                    cleaned = cleaned[4:].strip()

            result = json.loads(cleaned)
            return {
                "available": True,
                "message": "AI recommendations generated successfully.",
                "explanation": result.get("explanation", ""),
                "foods_to_eat": result.get("foods_to_eat", []),
                "foods_to_limit": result.get("foods_to_limit", []),
                "lifestyle_recommendations": result.get("lifestyle_recommendations", []),
                "disclaimer": result.get("disclaimer", "This is an AI-generated educational recommendation. It is not a medical diagnosis."),
            }
        except (error.HTTPError, error.URLError, json.JSONDecodeError, KeyError, ValueError) as exc:
            logger.exception("Gemini recommendation generation failed: %s", exc)
            return self._fallback_recommendation("AI recommendations are temporarily unavailable. Using built-in nutrition guidance instead.", context)
